# Generated by Django 4.2.23 on 2025-08-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project', max_length=100)),
                ('start_year', models.PositiveIntegerField(help_text='Year when the project started')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Year when the project ended', null=True)),
                ('start_month', models.PositiveIntegerField(help_text='Month when the project started')),
                ('end_month', models.PositiveIntegerField(blank=True, help_text='Month when the project ended', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Mark inactive if project got removed')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(default='REGULAR', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('present_days', models.FloatField(default=0)),
                ('billable_days', models.FloatField(default=0)),
                ('non_billable_days', models.FloatField(default=0)),
                ('billable_hours', models.FloatField(default=0, help_text='Leave empty to auto-calcuate')),
                ('non_billable_hours', models.FloatField(default=0, help_text='Leave empty to auto-calculate')),
                ('extra_hours', models.FloatField(blank=True, default=0, null=True)),
                ('poc', models.ManyToManyField(blank=True, related_name='assigned_poc', to='resources.resource')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attendance', to='projects.projects')),
                ('project_profile', models.ForeignKey(help_text='Main profile of the project', on_delete=django.db.models.deletion.PROTECT, related_name='project_profile', to='resources.resource')),
                ('resources', models.ManyToManyField(blank=True, related_name='assigned_resources', to='resources.resource')),
            ],
        ),
    ]
