# Generated by Django 4.2.23 on 2025-08-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattendance',
            name='project_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Project'), ('FIXED_COST', 'Fixed Cost Project')], default='REGULAR', max_length=20),
        ),
    ]
