# Generated by Django 4.2.23 on 2025-08-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectattendance_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectattendance',
            name='project_type',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(choices=[('REGULAR', 'Regular Project'), ('FIXED_COST', 'Fixed Cost Project')], default='REGULAR', max_length=20),
        ),
    ]
