# Generated by Django 4.2.23 on 2025-08-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(help_text='Full name of resource', max_length=100)),
                ('join_date', models.DateField(help_text='Date the resource joined')),
                ('leave_date', models.DateField(blank=True, help_text='Date the resource left(optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Mark inactive if resource left')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAttendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('working_days', models.FloatField(blank=True, help_text='Leave empty to auto-calculate', null=True)),
                ('present_day', models.FloatField(default=0)),
                ('present_hours', models.FloatField(default=0, help_text='Leave empty to auto-calculate')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_attendance', to='resources.resource')),
            ],
        ),
    ]
